### ISSUE TITLE
Serde Serialize fails, when using a too old date

### ISSUE THREAD

**Issue by Luro02** [Finnerale/untis-rs#1]
We use Webuntis in our school and we can only view 2 weeks in the future and 1 week in the past. Going past the 1 week limit gives me the following exception:
```
thread 'main' panicked at 'Failed to get timetable: SerdeJSON(Error("missing field `result`", line: 1, column: 78))', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Here is the full backtrace:
```
thread 'main' panicked at 'Failed to get timetable: SerdeJSON(Error("missing field `result`", line: 1, column: 78))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::expect
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:825
  10: mcuntis::main
             at src/main.rs:16
  11: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start
```

I requested the timetable and the following is my code (username and stuff has been removed :smirk: )
``` rust
type Result<T> = std::result::Result<T, std::io::Error>;
use untis::{ Units };
use chrono::{ Local, Utc, NaiveDate };

fn main() -> Result<()> {
    let mut untis = Units::new("nete", "", "", "");
    // let today = Local::today().naive_local();
    let today = NaiveDate::from_ymd(2019, 02, 10);
    let info = untis.login().expect("Failed to login");

    let _statusdata  = untis.status_data()                      .expect("Failed to get status data" );
    let _holidays    = untis.holidays()                         .expect("Failed to get holidays"    );
    let _rooms       = untis.rooms()                            .expect("Failed to get rooms"       );
    let _classes     = untis.classes()                          .expect("Failed to get classes"     );
    let _subjects    = untis.subjects()                         .expect("Failed to get subjects"    );
    let _timetable   = untis.timetable(info.class_id, 1, today) .expect("Failed to get timetable"   );
    let _departments = untis.departments()                      .expect("Failed to get departments" );
    // teachers
    println!("_timetable {:#?}", _timetable);
    println!("{:#?}", info.class_id);
    println!("{:#?}", info);
    untis.logout().expect("Failed to logout");
    Ok(())
}
```

**Comment by luleyleo** [comment]
Wow, I actually didn't expect that someone else would use this crate but you are welcome :joy: 

Regarding the exception you get: You are supposed to get an exception if anything failes due to the `.expect("Failed to get timetable");`, this can be improved to return a more specific error but it is basically telling that there was no result which seems ok to me.

If you only want to avoid exceptions, you could just do an
 `if let Some(timetable) = untis.timetable(...) {`
