### ISSUE TITLE
[bug] can't log in

### ISSUE THREAD

**Issue by jarjk** [Finnerale/untis-rs#10]
unfortunately I can't log in, although WebUntis does work.

version: latest, git

I've tried to do my best fixing it, but couldn't. The error comes from `src/jsonrpc.rs:102:64`, this line:
```rust
        let response: Response<T> = serde_json::from_str(&text)?;
```
below is all the information that I could get, (the second response is modified not to contain any potentionally personal data): 

```
RUST_BACKTRACE=full cargo r --example get_timetable
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/get_timetable`
response: {"result":{"size":0,"schools":[{"server":"mese.webuntis.com","useMobileServiceUrlAndroid":false,"address":"1010, Wien, Beethovenplatz 1","displayName":"Akademisches Gymnasium","loginName":"akg-wien","schoolId":7040900,"useMobileServiceUrlIos":false,"serverUrl":"https:\/\/mese.webuntis.com\/WebUntis\/?school=akg-wien","tenantId":"7040900","mobileServiceUrl":null}]},"id":"1","jsonrpc":"2.0"}
response: Ok { jsonrpc: "2.0", id: String("1"), result: SchoolSearchResult { size: 0, schools: [School { server: "mese.webuntis.com", use_mobile_service_url_android: false, address: "1010, Wien, Beethovenplatz 1", display_name: "Akademisches Gymnasium", login_name: "akg-wien", id: 7040900, use_mobile_service_url_ios: false, server_url: "https://mese.webuntis.com/WebUntis/?school=akg-wien", mobile_service_url: None }] } }
[examples/get_timetable.rs:9:5] &school = School {
    server: "mese.webuntis.com",
    use_mobile_service_url_android: false,
    address: "1010, Wien, Beethovenplatz 1",
    display_name: "Akademisches Gymnasium",
    login_name: "akg-wien",
    id: 7040900,
    use_mobile_service_url_ios: false,
    server_url: "https://mese.webuntis.com/WebUntis/?school=akg-wien",
    mobile_service_url: None,
}
response: {"jsonrpc":"2.0","id":"1","result":{"sessionId":"5BA00DD1D6742CCF0F80BB9A22705A5D","personType":0,"personId":0000,"klasseId":0000}}
thread 'main' panicked at src/client.rs:38:75:
called `Result::unwrap()` on an `Err` value: Serde(Error("data did not match any variant of untagged enum Response", line: 0, column: 0))
stack backtrace:
   0:     0x5ce70c7ae305 - std::backtrace_rs::backtrace::libunwind::trace::h649ab3318d3445c5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5ce70c7ae305 - std::backtrace_rs::backtrace::trace_unsynchronized::hf4bb60c3387150c3
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5ce70c7ae305 - std::sys::backtrace::_print_fmt::hd9186c800e44bd00
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:     0x5ce70c7ae305 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:     0x5ce70c7d403b - core::fmt::rt::Argument::fmt::h351a7824f737a6a0
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:     0x5ce70c7d403b - core::fmt::write::h4b5a1270214bc4a7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:     0x5ce70c7ab3ff - std::io::Write::write_fmt::hd04af345a50c312d
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:     0x5ce70c7af451 - std::sys::backtrace::BacktraceLock::print::h68d41b51481bce5c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:     0x5ce70c7af451 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:     0x5ce70c7af12c - std::panicking::default_hook::h3cacb9c27561ad33
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:     0x5ce70c7afb21 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:     0x5ce70c7af987 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
  12:     0x5ce70c7ae7c9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:     0x5ce70c7af614 - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:     0x5ce70c7d2153 - core::panicking::panic_fmt::h3d8fc78294164da7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  15:     0x5ce70c7d26a6 - core::result::unwrap_failed::hfa79a499befff387
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
  16:     0x5ce70c2ba9d6 - core::result::Result<T,E>::unwrap::h4df040aa0653bfc2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
  17:     0x5ce70c2ba9d6 - untis::client::Client::login::h201cfd1a25aa55ca
                               at /home/jero/Dev/rust/cloned/untis-rs/src/client.rs:38:32
  18:     0x5ce70c2b9a08 - untis::client::<impl untis::resources::School>::client_login::h825d56920386d140
                               at /home/jero/Dev/rust/cloned/untis-rs/src/client.rs:210:9
  19:     0x5ce70c25c8b5 - get_timetable::main::h90bb128b58fac0cf
                               at /home/jero/Dev/rust/cloned/untis-rs/examples/get_timetable.rs:12:18
  20:     0x5ce70c25dee2 - core::ops::function::FnOnce::call_once::hc68f17fec40451b6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  21:     0x5ce70c25db05 - std::sys::backtrace::__rust_begin_short_backtrace::hacf655117eedb452
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
  22:     0x5ce70c25ddd6 - std::rt::lang_start::{{closure}}::h90d207dd269d8fd2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
  23:     0x5ce70c7a6b80 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2feec6363bd28ad6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
  24:     0x5ce70c7a6b80 - std::panicking::try::do_call::h71b24ad3a8e797d5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  25:     0x5ce70c7a6b80 - std::panicking::try::h8412d1bfb4bcbcc1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  26:     0x5ce70c7a6b80 - std::panic::catch_unwind::h2053d3ee5bd8db53
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  27:     0x5ce70c7a6b80 - std::rt::lang_start_internal::{{closure}}::h82eb98fe4f8e75b8
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
  28:     0x5ce70c7a6b80 - std::panicking::try::do_call::h793dba66a0bbd3de
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  29:     0x5ce70c7a6b80 - std::panicking::try::he09b629b3ba06846
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  30:     0x5ce70c7a6b80 - std::panic::catch_unwind::h7964c913fc871155
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  31:     0x5ce70c7a6b80 - std::rt::lang_start_internal::h5e7c81cecd7f0954
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
  32:     0x5ce70c25ddaa - std::rt::lang_start::h41fe3b1945079330
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
  33:     0x5ce70c25d25e - main
  34:     0x758514745e08 - <unknown>
  35:     0x758514745ecc - __libc_start_main
  36:     0x5ce70c25bb45 - _start
  37:                0x0 - <unknown>
```

**Comment by arnimattr** [comment]
Your session's `personType: 0` is [currently not handled as a valid ElementType](https://github.com/luleyleo/untis-rs/blob/5fea7e9abc92f8c139ecf90899fe770ad0bc051d/src/resources.rs#L8-L13), which only allows the values 1-5. Do you have your own student/teacher credentials or a shared `#anonymous#` user for the entire school?
So far I've only seen personalized student credentials, a shared login could explain the absence of any other element type or id.
